[pytest]
# Parametro para definir los archivos que se van a ejecutar (Todos "test_")
python_files= test_*.py
python_clases= Test*
python_functions = test_*
addopts = -v --html=report.html --self-contained-html
